version: '3.9'

services:
  notebook:
    container_name: createtoolagi
    image: jupyter/datascience-notebook
    #ports:
    #  - '8090:8090'
    environment:
      - JUPYTER_ENABLE_LAB=yes
    volumes:
      - /Users/tanakatouma/vscode/CreateTool-AGI/:/home/CreateTool-AGI/
    command: start-notebook.sh --NotebookApp.token=''